/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fr.miage.toulouse.l3.gestiondesetudiants.view;

/**
 *
 * @author SophiaNachin
 */
public class B_ListeEtudiants extends javax.swing.JFrame {

    /**
     * Creates new form B_ListeUE
     */
    public B_ListeEtudiants() {
        initComponents();
        this.setLocationRelativeTo(null); // center the frame
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        HeaderPanel = new javax.swing.JPanel();
        AccueilButton = new javax.swing.JButton();
        InsButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        SearchBarTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        InsButton1 = new javax.swing.JButton();
        listeEtudiantLabel = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        annulerButton1 = new javax.swing.JButton();
        sauvegarderButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        FileMenu = new javax.swing.JMenu();
        EditMenu = new javax.swing.JMenu();
        ViewMenu2 = new javax.swing.JMenu();
        HelpMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        HeaderPanel.setBackground(new java.awt.Color(255, 172, 127));

        AccueilButton.setBackground(new java.awt.Color(255, 191, 153));
        AccueilButton.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        AccueilButton.setForeground(new java.awt.Color(90, 0, 255));
        AccueilButton.setText("Accueil");
        AccueilButton.setBorderPainted(false);
        AccueilButton.setContentAreaFilled(false);
        AccueilButton.setFocusPainted(false);
        AccueilButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccueilButtonActionPerformed(evt);
            }
        });

        InsButton.setBackground(new java.awt.Color(255, 191, 153));
        InsButton.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        InsButton.setForeground(new java.awt.Color(90, 0, 255));
        InsButton.setText("Saisie des résultats");
        InsButton.setBorderPainted(false);
        InsButton.setContentAreaFilled(false);
        InsButton.setFocusPainted(false);
        InsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel1.setText(">");

        SearchBarTextField1.setFont(new java.awt.Font("Segoe UI", 2, 13)); // NOI18N
        SearchBarTextField1.setForeground(new java.awt.Color(153, 153, 153));
        SearchBarTextField1.setText("Rechercher un étudiant");
        SearchBarTextField1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(204, 204, 204)));
        SearchBarTextField1.setDisabledTextColor(new java.awt.Color(102, 255, 102));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel2.setText(">");

        InsButton1.setBackground(new java.awt.Color(255, 191, 153));
        InsButton1.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        InsButton1.setForeground(new java.awt.Color(51, 51, 51));
        InsButton1.setText("Liste des étudiants");
        InsButton1.setBorderPainted(false);
        InsButton1.setContentAreaFilled(false);
        InsButton1.setFocusPainted(false);
        InsButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout HeaderPanelLayout = new javax.swing.GroupLayout(HeaderPanel);
        HeaderPanel.setLayout(HeaderPanelLayout);
        HeaderPanelLayout.setHorizontalGroup(
            HeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderPanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(AccueilButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InsButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InsButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SearchBarTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        HeaderPanelLayout.setVerticalGroup(
            HeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(HeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AccueilButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(InsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addComponent(SearchBarTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(InsButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );

        listeEtudiantLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        listeEtudiantLabel.setForeground(new java.awt.Color(51, 51, 51));
        listeEtudiantLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        listeEtudiantLabel.setText("Liste des étudiants");

        jTable4.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jTable4.setForeground(new java.awt.Color(51, 51, 51));
        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "N° étudiant", "Nom de l'étudiant", "Prénom de l'étudiant", "Mention de l'ue"
            }
        ));
        jTable4.setGridColor(new java.awt.Color(204, 204, 204));
        jTable4.setSelectionBackground(new java.awt.Color(0, 165, 255));
        jScrollPane4.setViewportView(jTable4);

        annulerButton1.setBackground(new java.awt.Color(255, 0, 38));
        annulerButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        annulerButton1.setForeground(new java.awt.Color(51, 51, 51));
        annulerButton1.setText("Annuler");
        annulerButton1.setFocusPainted(false);
        annulerButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annulerButton1ActionPerformed(evt);
            }
        });

        sauvegarderButton.setBackground(new java.awt.Color(0, 255, 90));
        sauvegarderButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        sauvegarderButton.setForeground(new java.awt.Color(51, 51, 51));
        sauvegarderButton.setText("Sauvegarder");
        sauvegarderButton.setFocusPainted(false);
        sauvegarderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sauvegarderButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HeaderPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 762, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(listeEtudiantLabel))
                .addContainerGap(48, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(annulerButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(136, 136, 136)
                .addComponent(sauvegarderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(214, 214, 214))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(HeaderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(listeEtudiantLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sauvegarderButton)
                    .addComponent(annulerButton1))
                .addGap(26, 26, 26))
        );

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));

        FileMenu.setBackground(new java.awt.Color(255, 255, 255));
        FileMenu.setForeground(new java.awt.Color(51, 51, 51));
        FileMenu.setText("File");
        jMenuBar1.add(FileMenu);

        EditMenu.setBackground(new java.awt.Color(255, 255, 255));
        EditMenu.setForeground(new java.awt.Color(51, 51, 51));
        EditMenu.setText("Edit");
        jMenuBar1.add(EditMenu);

        ViewMenu2.setBackground(new java.awt.Color(255, 255, 255));
        ViewMenu2.setForeground(new java.awt.Color(51, 51, 51));
        ViewMenu2.setText("View");
        jMenuBar1.add(ViewMenu2);

        HelpMenu1.setBackground(new java.awt.Color(255, 255, 255));
        HelpMenu1.setForeground(new java.awt.Color(51, 51, 51));
        HelpMenu1.setText("Help");
        jMenuBar1.add(HelpMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AccueilButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccueilButtonActionPerformed
        this.dispose();
        Accueil acc = new Accueil();
        acc.setVisible(true);
    }//GEN-LAST:event_AccueilButtonActionPerformed

    private void InsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InsButtonActionPerformed

    private void sauvegarderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sauvegarderButtonActionPerformed
        
    }//GEN-LAST:event_sauvegarderButtonActionPerformed

    private void InsButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InsButton1ActionPerformed

    private void annulerButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annulerButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_annulerButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(B_ListeEtudiants.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(B_ListeEtudiants.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(B_ListeEtudiants.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(B_ListeEtudiants.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new B_ListeEtudiants().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AccueilButton;
    private javax.swing.JMenu EditMenu;
    private javax.swing.JMenu FileMenu;
    private javax.swing.JPanel HeaderPanel;
    private javax.swing.JMenu HelpMenu1;
    private javax.swing.JButton InsButton;
    private javax.swing.JButton InsButton1;
    private javax.swing.JTextField SearchBarTextField1;
    private javax.swing.JMenu ViewMenu2;
    private javax.swing.JButton annulerButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable4;
    private javax.swing.JLabel listeEtudiantLabel;
    private javax.swing.JButton sauvegarderButton;
    // End of variables declaration//GEN-END:variables
}
