package fr.miage.toulouse.l3.gestiondesetudiants.view;

/**
 *
 * @author SophiaNachin
 */
public class BureauExamenListeEtudiantsPanel extends javax.swing.JPanel {

    /**
     * Creates new form BureauExamenListeEtudiantsPanel
     */
    public BureauExamenListeEtudiantsPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        listeEtudiantLabel = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        annulerButton1 = new javax.swing.JButton();
        sauvegarderButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(252, 252, 252));
        setPreferredSize(new java.awt.Dimension(709, 509));

        listeEtudiantLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        listeEtudiantLabel.setForeground(new java.awt.Color(51, 51, 51));
        listeEtudiantLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        listeEtudiantLabel.setText("Liste des étudiants");

        jScrollPane4.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane4.setForeground(new java.awt.Color(51, 51, 51));

        jTable4.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jTable4.setForeground(new java.awt.Color(51, 51, 51));
        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "N° étudiant", "Nom de l'étudiant", "Prénom de l'étudiant", "Mention de l'ue"
            }
        ));
        jTable4.setGridColor(new java.awt.Color(255, 255, 255));
        jTable4.setSelectionBackground(new java.awt.Color(0, 165, 255));
        jScrollPane4.setViewportView(jTable4);

        annulerButton1.setBackground(new java.awt.Color(255, 0, 38));
        annulerButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        annulerButton1.setForeground(new java.awt.Color(51, 51, 51));
        annulerButton1.setText("Annuler");
        annulerButton1.setFocusPainted(false);
        annulerButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annulerButton1ActionPerformed(evt);
            }
        });

        sauvegarderButton.setBackground(new java.awt.Color(0, 255, 90));
        sauvegarderButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        sauvegarderButton.setForeground(new java.awt.Color(51, 51, 51));
        sauvegarderButton.setText("Sauvegarder");
        sauvegarderButton.setFocusPainted(false);
        sauvegarderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sauvegarderButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 132, Short.MAX_VALUE)
                        .addComponent(annulerButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(131, 131, 131)
                        .addComponent(sauvegarderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 132, Short.MAX_VALUE))
                    .addComponent(listeEtudiantLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(9, 9, 9)
                    .addComponent(jScrollPane4)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(listeEtudiantLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 405, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(annulerButton1)
                    .addComponent(sauvegarderButton))
                .addGap(20, 20, 20))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(69, 69, 69)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE)
                    .addGap(75, 75, 75)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void annulerButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annulerButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_annulerButton1ActionPerformed

    private void sauvegarderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sauvegarderButtonActionPerformed

    }//GEN-LAST:event_sauvegarderButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton annulerButton1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable4;
    private javax.swing.JLabel listeEtudiantLabel;
    private javax.swing.JButton sauvegarderButton;
    // End of variables declaration//GEN-END:variables
}
