/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fr.miage.toulouse.l3.gestiondesetudiants.view;

import fr.miage.toulouse.l3.gestiondesetudiants.modele.ListeUeEnCoursCsv;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStreamReader;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import org.apache.commons.csv.CSVFormat;
import org.apache.commons.csv.CSVParser;
import org.apache.commons.csv.CSVRecord;
import javax.swing.JTable;


/**
 *
 * @author SophiaNachin
 */
public class DirectDossierEtudiant extends javax.swing.JFrame {   
    //private ListeUeEnCoursCsv myListEnCours;
    //private Object[][] data;
    //private String [] columnNames = {"Code id de l'UE", "Nom UE", "Crédits ECTS"};
    //DefaultTableModel tableModel;
    public static String numEtudiant;
    /**
     * Creates new form DS_DossierEtudiant
     */
    public DirectDossierEtudiant() {
        super("Dossier étudiant");
        this.setLocationRelativeTo(null); // center the frame
        initComponents();
        
        /*myListEnCours = new ListeUeEnCoursCsv();
        
        String str = "donnees/21801011_ListeUeEnCours.csv";
        myListEnCours.readFromCSV(str);
        data = myListEnCours.convert2Data();
        tableModel = new DefaultTableModel(data, columnNames);
        
       
        //UeEnCoursjTable = new JTable(tableModel);
        //association data,columnsName dans initComponents()
        //ajout de mouseListener dans initComponents()  
        */
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        HeaderPanel = new javax.swing.JPanel();
        AccueilButton = new javax.swing.JButton();
        VisConButton = new javax.swing.JButton();
        DosButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        SearchBarTextField1 = new javax.swing.JTextField();
        DseLayeredPane1 = new javax.swing.JLayeredPane();
        titleDossierLabel = new javax.swing.JLabel();
        titleNumEtudiantLabel = new javax.swing.JLabel();
        numEtudiantLabel = new javax.swing.JLabel();
        titleNomLabel = new javax.swing.JLabel();
        nomLabel = new javax.swing.JLabel();
        titlePrenomLabel = new javax.swing.JLabel();
        prenomLabel = new javax.swing.JLabel();
        titleMentionLabel = new javax.swing.JLabel();
        mentionLabel = new javax.swing.JLabel();
        titleParcoursLabel = new javax.swing.JLabel();
        parcoursLabel = new javax.swing.JLabel();
        listeUEPanel = new javax.swing.JPanel();
        ListeUETabbedPane = new javax.swing.JTabbedPane();
        UeEnCoursJTabbedPane = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        UeEnCoursjTable = new javax.swing.JTable();
        jLabel18 = new javax.swing.JLabel();
        UeDisponibleJTabbedPane = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        UeDisponibleJTable = new javax.swing.JTable();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        UeValideeJTabbedPane = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        UeValideejTable = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        listeUELabel = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        FileMenu = new javax.swing.JMenu();
        EditMenu = new javax.swing.JMenu();
        ViewMenu2 = new javax.swing.JMenu();
        HelpMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        HeaderPanel.setBackground(new java.awt.Color(255, 172, 127));

        AccueilButton.setBackground(new java.awt.Color(255, 191, 153));
        AccueilButton.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        AccueilButton.setForeground(new java.awt.Color(90, 0, 255));
        AccueilButton.setText("Accueil");
        AccueilButton.setBorderPainted(false);
        AccueilButton.setContentAreaFilled(false);
        AccueilButton.setFocusPainted(false);
        AccueilButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccueilButtonActionPerformed(evt);
            }
        });

        VisConButton.setBackground(new java.awt.Color(255, 191, 153));
        VisConButton.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        VisConButton.setForeground(new java.awt.Color(90, 0, 255));
        VisConButton.setText("Visualisation et conseil");
        VisConButton.setBorderPainted(false);
        VisConButton.setContentAreaFilled(false);
        VisConButton.setFocusPainted(false);
        VisConButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VisConButtonActionPerformed(evt);
            }
        });

        DosButton.setBackground(new java.awt.Color(255, 191, 153));
        DosButton.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        DosButton.setText("Dossier Étudiant");
        DosButton.setBorderPainted(false);
        DosButton.setContentAreaFilled(false);
        DosButton.setFocusPainted(false);
        DosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DosButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel1.setText(">");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel2.setText(">");

        SearchBarTextField1.setFont(new java.awt.Font("Segoe UI", 2, 13)); // NOI18N
        SearchBarTextField1.setForeground(new java.awt.Color(102, 102, 102));
        SearchBarTextField1.setText("Rechercher un étudiant");
        SearchBarTextField1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(204, 204, 204)));

        javax.swing.GroupLayout HeaderPanelLayout = new javax.swing.GroupLayout(HeaderPanel);
        HeaderPanel.setLayout(HeaderPanelLayout);
        HeaderPanelLayout.setHorizontalGroup(
            HeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderPanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(AccueilButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(VisConButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DosButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                .addComponent(SearchBarTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );
        HeaderPanelLayout.setVerticalGroup(
            HeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(HeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AccueilButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DosButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(VisConButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(SearchBarTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        titleDossierLabel.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        titleDossierLabel.setForeground(new java.awt.Color(51, 51, 51));
        titleDossierLabel.setText("Dossier de : ");

        titleNumEtudiantLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        titleNumEtudiantLabel.setForeground(new java.awt.Color(51, 51, 51));
        titleNumEtudiantLabel.setText("N° étudiant");

        numEtudiantLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        numEtudiantLabel.setForeground(new java.awt.Color(51, 51, 51));
        numEtudiantLabel.setText("jLabel3");

        titleNomLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        titleNomLabel.setForeground(new java.awt.Color(51, 51, 51));
        titleNomLabel.setText("Nom");

        nomLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nomLabel.setForeground(new java.awt.Color(51, 51, 51));
        nomLabel.setText("jLabel3");

        titlePrenomLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        titlePrenomLabel.setForeground(new java.awt.Color(51, 51, 51));
        titlePrenomLabel.setText("Prénom");

        prenomLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        prenomLabel.setForeground(new java.awt.Color(51, 51, 51));
        prenomLabel.setText("jLabel3");

        titleMentionLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        titleMentionLabel.setForeground(new java.awt.Color(51, 51, 51));
        titleMentionLabel.setText("Mention");

        mentionLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mentionLabel.setForeground(new java.awt.Color(51, 51, 51));
        mentionLabel.setText("jLabel3");

        titleParcoursLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        titleParcoursLabel.setForeground(new java.awt.Color(51, 51, 51));
        titleParcoursLabel.setText("Parcours");

        parcoursLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        parcoursLabel.setForeground(new java.awt.Color(51, 51, 51));
        parcoursLabel.setText("jLabel3");

        DseLayeredPane1.setLayer(titleDossierLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DseLayeredPane1.setLayer(titleNumEtudiantLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DseLayeredPane1.setLayer(numEtudiantLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DseLayeredPane1.setLayer(titleNomLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DseLayeredPane1.setLayer(nomLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DseLayeredPane1.setLayer(titlePrenomLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DseLayeredPane1.setLayer(prenomLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DseLayeredPane1.setLayer(titleMentionLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DseLayeredPane1.setLayer(mentionLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DseLayeredPane1.setLayer(titleParcoursLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DseLayeredPane1.setLayer(parcoursLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout DseLayeredPane1Layout = new javax.swing.GroupLayout(DseLayeredPane1);
        DseLayeredPane1.setLayout(DseLayeredPane1Layout);
        DseLayeredPane1Layout.setHorizontalGroup(
            DseLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DseLayeredPane1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(titleDossierLabel)
                .addGap(24, 24, 24)
                .addGroup(DseLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(numEtudiantLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(titleNumEtudiantLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(DseLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nomLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                    .addComponent(titleNomLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(DseLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titlePrenomLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prenomLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(DseLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titleMentionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mentionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(DseLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titleParcoursLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(parcoursLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        DseLayeredPane1Layout.setVerticalGroup(
            DseLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DseLayeredPane1Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(DseLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleNomLabel)
                    .addComponent(titlePrenomLabel)
                    .addComponent(titleMentionLabel)
                    .addComponent(titleParcoursLabel)
                    .addComponent(titleDossierLabel)
                    .addComponent(titleNumEtudiantLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DseLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numEtudiantLabel)
                    .addComponent(nomLabel)
                    .addComponent(prenomLabel)
                    .addComponent(mentionLabel)
                    .addComponent(parcoursLabel))
                .addGap(29, 29, 29))
        );

        listeUEPanel.setBackground(new java.awt.Color(252, 252, 252));

        ListeUETabbedPane.setBackground(new java.awt.Color(255, 255, 255));
        ListeUETabbedPane.setForeground(new java.awt.Color(51, 51, 51));
        ListeUETabbedPane.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        UeEnCoursJTabbedPane.setBackground(new java.awt.Color(255, 255, 255));
        UeEnCoursJTabbedPane.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N

        jScrollPane3.setBackground(new java.awt.Color(255, 255, 255));

        UeEnCoursjTable.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        UeEnCoursjTable.setForeground(new java.awt.Color(51, 51, 51));
        UeEnCoursjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                //"Code id de l'UE", "Nom UE", "Crédits ECTS"
            }
        )
    );
    UeEnCoursjTable.setGridColor(new java.awt.Color(255, 255, 255));
    UeEnCoursjTable.setSelectionBackground(new java.awt.Color(255, 191, 153));
    jScrollPane3.setViewportView(UeEnCoursjTable);

    jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    jLabel18.setForeground(new java.awt.Color(51, 51, 51));
    jLabel18.setText("2020-2021 - 3ème année - premier semestre");

    javax.swing.GroupLayout UeEnCoursJTabbedPaneLayout = new javax.swing.GroupLayout(UeEnCoursJTabbedPane);
    UeEnCoursJTabbedPane.setLayout(UeEnCoursJTabbedPaneLayout);
    UeEnCoursJTabbedPaneLayout.setHorizontalGroup(
        UeEnCoursJTabbedPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(UeEnCoursJTabbedPaneLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(UeEnCoursJTabbedPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 734, Short.MAX_VALUE)
                .addGroup(UeEnCoursJTabbedPaneLayout.createSequentialGroup()
                    .addComponent(jLabel18)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addContainerGap())
    );
    UeEnCoursJTabbedPaneLayout.setVerticalGroup(
        UeEnCoursJTabbedPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(UeEnCoursJTabbedPaneLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel18)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
            .addContainerGap())
    );

    ListeUETabbedPane.addTab("UE en cours", UeEnCoursJTabbedPane);

    UeDisponibleJTabbedPane.setBackground(new java.awt.Color(255, 255, 255));

    jScrollPane4.setBackground(new java.awt.Color(255, 255, 255));

    UeDisponibleJTable.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
    UeDisponibleJTable.setForeground(new java.awt.Color(51, 51, 51));
    UeDisponibleJTable.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {

        },
        new String [] {

        }
    ));
    UeDisponibleJTable.setGridColor(new java.awt.Color(204, 204, 204));
    UeDisponibleJTable.setSelectionBackground(new java.awt.Color(255, 191, 153));
    jScrollPane4.setViewportView(UeDisponibleJTable);

    jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    jLabel19.setForeground(new java.awt.Color(51, 51, 51));

    jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    jLabel20.setForeground(new java.awt.Color(51, 51, 51));
    jLabel20.setText("Trier par");

    jComboBox1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    jComboBox1.setForeground(new java.awt.Color(51, 51, 51));
    jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Parcours", "Item 2", "Item 3", "Item 4" }));
    jComboBox1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jComboBox1ActionPerformed(evt);
        }
    });

    jComboBox2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    jComboBox2.setForeground(new java.awt.Color(51, 51, 51));
    jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Niveau", "Item 2", "Item 3", "Item 4" }));
    jComboBox2.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jComboBox2ActionPerformed(evt);
        }
    });

    jComboBox3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    jComboBox3.setForeground(new java.awt.Color(51, 51, 51));
    jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mention", "Item 2", "Item 3", "Item 4" }));
    jComboBox3.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jComboBox3ActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout UeDisponibleJTabbedPaneLayout = new javax.swing.GroupLayout(UeDisponibleJTabbedPane);
    UeDisponibleJTabbedPane.setLayout(UeDisponibleJTabbedPaneLayout);
    UeDisponibleJTabbedPaneLayout.setHorizontalGroup(
        UeDisponibleJTabbedPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(UeDisponibleJTabbedPaneLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(UeDisponibleJTabbedPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 734, Short.MAX_VALUE)
                .addGroup(UeDisponibleJTabbedPaneLayout.createSequentialGroup()
                    .addComponent(jLabel19)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel20)
                    .addGap(18, 18, 18)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addContainerGap())
    );
    UeDisponibleJTabbedPaneLayout.setVerticalGroup(
        UeDisponibleJTabbedPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(UeDisponibleJTabbedPaneLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(UeDisponibleJTabbedPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel19)
                .addComponent(jLabel20)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
            .addContainerGap())
    );

    ListeUETabbedPane.addTab("UE Disponible", UeDisponibleJTabbedPane);

    UeValideeJTabbedPane.setBackground(new java.awt.Color(255, 255, 255));

    jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));

    UeValideejTable.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
    UeValideejTable.setForeground(new java.awt.Color(51, 51, 51));
    UeValideejTable.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {

        },
        new String [] {

        }
    ));
    UeValideejTable.setGridColor(new java.awt.Color(255, 255, 255));
    UeValideejTable.setSelectionBackground(new java.awt.Color(255, 191, 153));
    jScrollPane2.setViewportView(UeValideejTable);
    if (UeValideejTable.getColumnModel().getColumnCount() > 0) {
        UeValideejTable.getColumnModel().getColumn(5).setHeaderValue("Année obtention");
        UeValideejTable.getColumnModel().getColumn(6).setHeaderValue("Session");
    }

    jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    jLabel14.setText("2020-2021 - 3ème année - UE validées");

    javax.swing.GroupLayout UeValideeJTabbedPaneLayout = new javax.swing.GroupLayout(UeValideeJTabbedPane);
    UeValideeJTabbedPane.setLayout(UeValideeJTabbedPaneLayout);
    UeValideeJTabbedPaneLayout.setHorizontalGroup(
        UeValideeJTabbedPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(UeValideeJTabbedPaneLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(UeValideeJTabbedPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 734, Short.MAX_VALUE)
                .addGroup(UeValideeJTabbedPaneLayout.createSequentialGroup()
                    .addComponent(jLabel14)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addContainerGap())
    );
    UeValideeJTabbedPaneLayout.setVerticalGroup(
        UeValideeJTabbedPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(UeValideeJTabbedPaneLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel14)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
            .addContainerGap())
    );

    ListeUETabbedPane.addTab("UE validée", UeValideeJTabbedPane);

    listeUELabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
    listeUELabel.setForeground(new java.awt.Color(51, 51, 51));
    listeUELabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    listeUELabel.setText("Liste des UE");

    javax.swing.GroupLayout listeUEPanelLayout = new javax.swing.GroupLayout(listeUEPanel);
    listeUEPanel.setLayout(listeUEPanelLayout);
    listeUEPanelLayout.setHorizontalGroup(
        listeUEPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(listeUEPanelLayout.createSequentialGroup()
            .addGap(371, 371, 371)
            .addComponent(listeUELabel)
            .addContainerGap(388, Short.MAX_VALUE))
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, listeUEPanelLayout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ListeUETabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 759, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(66, 66, 66))
    );
    listeUEPanelLayout.setVerticalGroup(
        listeUEPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, listeUEPanelLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(listeUELabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(ListeUETabbedPane)
            .addContainerGap())
    );

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(HeaderPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(DseLayeredPane1)
        .addComponent(listeUEPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addComponent(HeaderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(DseLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(listeUEPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
    );

    jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));

    FileMenu.setBackground(new java.awt.Color(255, 255, 255));
    FileMenu.setForeground(new java.awt.Color(51, 51, 51));
    FileMenu.setText("File");
    jMenuBar1.add(FileMenu);

    EditMenu.setBackground(new java.awt.Color(255, 255, 255));
    EditMenu.setForeground(new java.awt.Color(51, 51, 51));
    EditMenu.setText("Edit");
    jMenuBar1.add(EditMenu);

    ViewMenu2.setBackground(new java.awt.Color(255, 255, 255));
    ViewMenu2.setForeground(new java.awt.Color(51, 51, 51));
    ViewMenu2.setText("View");
    jMenuBar1.add(ViewMenu2);

    HelpMenu1.setBackground(new java.awt.Color(255, 255, 255));
    HelpMenu1.setForeground(new java.awt.Color(51, 51, 51));
    HelpMenu1.setText("Help");
    jMenuBar1.add(HelpMenu1);

    setJMenuBar(jMenuBar1);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DosButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DosButtonActionPerformed

    private void VisConButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VisConButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VisConButtonActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void AccueilButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccueilButtonActionPerformed
        this.dispose();
        Accueil acc = new Accueil();
        acc.setVisible(true);
    }//GEN-LAST:event_AccueilButtonActionPerformed
    
    
    public javax.swing.JLabel getnumEtudiantLabel(){
        return this.numEtudiantLabel;
    }
    
    public javax.swing.JLabel getNomLabel(){
        return this.nomLabel;
    }
    
    public javax.swing.JLabel getPrenomLabel(){
        return this.prenomLabel;
    }
    
    /*public javax.swing.JLabel getNiveauLabel(){
        return this.niveauLabel;
    }*/
    
    public javax.swing.JLabel getMentionLabel(){
        return this.mentionLabel;
    }
    
    public javax.swing.JLabel getParcoursLabel(){
        return this.parcoursLabel;
    }

    public JTable getUeEnCoursjTable() {
        return UeEnCoursjTable;
    }

    public JTable getUeValideejTable() {
        return UeValideejTable;
    }

    public JTable getUeDisponibleJTable() {
        return UeDisponibleJTable;
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DirectDossierEtudiant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DirectDossierEtudiant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DirectDossierEtudiant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DirectDossierEtudiant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

    }
    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AccueilButton;
    private javax.swing.JButton DosButton;
    private javax.swing.JLayeredPane DseLayeredPane1;
    private javax.swing.JMenu EditMenu;
    private javax.swing.JMenu FileMenu;
    private javax.swing.JPanel HeaderPanel;
    private javax.swing.JMenu HelpMenu1;
    private javax.swing.JTabbedPane ListeUETabbedPane;
    private javax.swing.JTextField SearchBarTextField1;
    private javax.swing.JPanel UeDisponibleJTabbedPane;
    private javax.swing.JTable UeDisponibleJTable;
    private javax.swing.JPanel UeEnCoursJTabbedPane;
    private javax.swing.JTable UeEnCoursjTable;
    private javax.swing.JPanel UeValideeJTabbedPane;
    private javax.swing.JTable UeValideejTable;
    private javax.swing.JMenu ViewMenu2;
    private javax.swing.JButton VisConButton;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel listeUELabel;
    private javax.swing.JPanel listeUEPanel;
    private javax.swing.JLabel mentionLabel;
    private javax.swing.JLabel nomLabel;
    private javax.swing.JLabel numEtudiantLabel;
    private javax.swing.JLabel parcoursLabel;
    private javax.swing.JLabel prenomLabel;
    private javax.swing.JLabel titleDossierLabel;
    private javax.swing.JLabel titleMentionLabel;
    private javax.swing.JLabel titleNomLabel;
    private javax.swing.JLabel titleNumEtudiantLabel;
    private javax.swing.JLabel titleParcoursLabel;
    private javax.swing.JLabel titlePrenomLabel;
    // End of variables declaration//GEN-END:variables

}
