package fr.miage.toulouse.l3.gestiondesetudiants.view;

/**
 *
 * @author SophiaNachin
 */
public class DirectDossierEtudiantPanel extends javax.swing.JPanel {

    /**
     * Creates new form BureauExamenListeEtudiantsPanel
     */
    public DirectDossierEtudiantPanel() {
        initComponents();  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        listeUEPanel = new javax.swing.JPanel();
        listeUELabel = new javax.swing.JLabel();
        directUeEnCoursButton2 = new fr.miage.toulouse.l3.gestiondesetudiants.controller.DirectUeEnCoursButton();
        directUeValiderButton2 = new fr.miage.toulouse.l3.gestiondesetudiants.controller.DirectUeValiderButton();
        directUeDisponibleButton2 = new fr.miage.toulouse.l3.gestiondesetudiants.controller.DirectUeDisponibleButton();
        parcoursComboBox = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        listeUeTable2 = new fr.miage.toulouse.l3.gestiondesetudiants.view.ListeUeTable();
        directMentionJComboBox1 = new fr.miage.toulouse.l3.gestiondesetudiants.controller.DirectMentionJComboBox();
        dossierEtudiantPanel1 = new fr.miage.toulouse.l3.gestiondesetudiants.view.DossierEtudiantPanel();

        setBackground(new java.awt.Color(252, 252, 252));
        setPreferredSize(new java.awt.Dimension(709, 509));

        listeUEPanel.setBackground(new java.awt.Color(252, 252, 252));

        listeUELabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        listeUELabel.setForeground(new java.awt.Color(51, 51, 51));
        listeUELabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        listeUELabel.setText("Liste des UE");

        parcoursComboBox.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        parcoursComboBox.setForeground(new java.awt.Color(51, 51, 51));
        parcoursComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Parcours" }));
        parcoursComboBox.setEnabled(false);

        listeUeTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(listeUeTable2);

        javax.swing.GroupLayout listeUEPanelLayout = new javax.swing.GroupLayout(listeUEPanel);
        listeUEPanel.setLayout(listeUEPanelLayout);
        listeUEPanelLayout.setHorizontalGroup(
            listeUEPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listeUEPanelLayout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(listeUELabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(97, 97, 97))
            .addGroup(listeUEPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(directUeEnCoursButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(directUeValiderButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(directUeDisponibleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(directMentionJComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(parcoursComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(listeUEPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        listeUEPanelLayout.setVerticalGroup(
            listeUEPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, listeUEPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(listeUELabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(listeUEPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(directUeEnCoursButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(listeUEPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(directUeValiderButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(directUeDisponibleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(parcoursComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(directMentionJComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(listeUEPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(dossierEtudiantPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(dossierEtudiantPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(listeUEPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private fr.miage.toulouse.l3.gestiondesetudiants.controller.DirectMentionJComboBox directMentionJComboBox1;
    private fr.miage.toulouse.l3.gestiondesetudiants.controller.DirectUeDisponibleButton directUeDisponibleButton2;
    private fr.miage.toulouse.l3.gestiondesetudiants.controller.DirectUeEnCoursButton directUeEnCoursButton2;
    private fr.miage.toulouse.l3.gestiondesetudiants.controller.DirectUeValiderButton directUeValiderButton2;
    private fr.miage.toulouse.l3.gestiondesetudiants.view.DossierEtudiantPanel dossierEtudiantPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel listeUELabel;
    private javax.swing.JPanel listeUEPanel;
    private fr.miage.toulouse.l3.gestiondesetudiants.view.ListeUeTable listeUeTable2;
    private javax.swing.JComboBox<String> parcoursComboBox;
    // End of variables declaration//GEN-END:variables
}
