package fr.miage.toulouse.l3.gestiondesetudiants.view;

import fr.miage.toulouse.l3.gestiondesetudiants.modele.Etudiant;
import fr.miage.toulouse.l3.gestiondesetudiants.modele.Mention;
import fr.miage.toulouse.l3.gestiondesetudiants.modele.Parcours;
import fr.miage.toulouse.l3.gestiondesetudiants.modele.UE;
import java.util.ArrayList;

/**
 *
 * @author SophiaNachin
 */
public class DossierEtudiantPanel extends javax.swing.JPanel implements IView{

    /**
     * Creates new form BureauExamenListeEtudiantsPanel
     */
    public DossierEtudiantPanel() {
        /* ------------------------------------------------ */
        initComponents();
        Etudiant.getInstance().addView(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dossierPanel = new javax.swing.JPanel();
        titleDossierLabel1 = new javax.swing.JLabel();
        titleNumEtudiantLabel1 = new javax.swing.JLabel();
        titleNomLabel1 = new javax.swing.JLabel();
        titlePrenomLabel1 = new javax.swing.JLabel();
        titleMentionLabel1 = new javax.swing.JLabel();
        titleParcoursLabel1 = new javax.swing.JLabel();
        numEtudiant = new fr.miage.toulouse.l3.gestiondesetudiants.view.EtudiantLabel();
        nomEtudiant = new fr.miage.toulouse.l3.gestiondesetudiants.view.EtudiantLabel();
        prenomEtudiant = new fr.miage.toulouse.l3.gestiondesetudiants.view.EtudiantLabel();
        mentionEtudiant = new fr.miage.toulouse.l3.gestiondesetudiants.view.EtudiantLabel();
        parcoursEtudiant = new fr.miage.toulouse.l3.gestiondesetudiants.view.EtudiantLabel();

        setBackground(new java.awt.Color(252, 252, 252));
        setPreferredSize(new java.awt.Dimension(709, 70));

        dossierPanel.setBackground(new java.awt.Color(255, 255, 255));
        dossierPanel.setPreferredSize(new java.awt.Dimension(709, 70));

        titleDossierLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        titleDossierLabel1.setForeground(new java.awt.Color(51, 51, 51));
        titleDossierLabel1.setText("Dossier de : ");

        titleNumEtudiantLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        titleNumEtudiantLabel1.setForeground(new java.awt.Color(51, 51, 51));
        titleNumEtudiantLabel1.setText("N° étudiant");

        titleNomLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        titleNomLabel1.setForeground(new java.awt.Color(51, 51, 51));
        titleNomLabel1.setText("Nom");

        titlePrenomLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        titlePrenomLabel1.setForeground(new java.awt.Color(51, 51, 51));
        titlePrenomLabel1.setText("Prénom");

        titleMentionLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        titleMentionLabel1.setForeground(new java.awt.Color(51, 51, 51));
        titleMentionLabel1.setText("Mention");

        titleParcoursLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        titleParcoursLabel1.setForeground(new java.awt.Color(51, 51, 51));
        titleParcoursLabel1.setText("Parcours");

        numEtudiant.setText("etudiantLabel1");

        nomEtudiant.setText("etudiantLabel2");

        prenomEtudiant.setText("etudiantLabel3");

        mentionEtudiant.setText("etudiantLabel4");

        parcoursEtudiant.setText("etudiantLabel5");

        javax.swing.GroupLayout dossierPanelLayout = new javax.swing.GroupLayout(dossierPanel);
        dossierPanel.setLayout(dossierPanelLayout);
        dossierPanelLayout.setHorizontalGroup(
            dossierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dossierPanelLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(titleDossierLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dossierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titleNumEtudiantLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numEtudiant, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dossierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titleNomLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomEtudiant, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dossierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titlePrenomLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prenomEtudiant, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dossierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titleMentionLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mentionEtudiant, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dossierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titleParcoursLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(parcoursEtudiant, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11))
        );
        dossierPanelLayout.setVerticalGroup(
            dossierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dossierPanelLayout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(dossierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(dossierPanelLayout.createSequentialGroup()
                        .addComponent(titleParcoursLabel1)
                        .addGap(22, 22, 22))
                    .addGroup(dossierPanelLayout.createSequentialGroup()
                        .addComponent(titleNomLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(dossierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(numEtudiant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nomEtudiant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(prenomEtudiant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mentionEtudiant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(parcoursEtudiant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(dossierPanelLayout.createSequentialGroup()
                        .addGroup(dossierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(titleMentionLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dossierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(titlePrenomLabel1)
                                .addComponent(titleDossierLabel1)
                                .addComponent(titleNumEtudiantLabel1)))
                        .addGap(22, 22, 22)))
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dossierPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dossierPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void notify(String numEt, String nom, String prenom, Mention mention, Parcours parcours) {
        this.numEtudiant.setText(""+ numEt);
        this.nomEtudiant.setText(""+ nom);
        this.prenomEtudiant.setText(""+ prenom);
        this.mentionEtudiant.setText("" + mention.getIntituleMention());
        this.parcoursEtudiant.setText("" +parcours.getIntituleParcours());
    }
    
    @Override
    public void notify(String[] columnNames, ArrayList<UE> listeUe) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel dossierPanel;
    private fr.miage.toulouse.l3.gestiondesetudiants.view.EtudiantLabel mentionEtudiant;
    private fr.miage.toulouse.l3.gestiondesetudiants.view.EtudiantLabel nomEtudiant;
    private fr.miage.toulouse.l3.gestiondesetudiants.view.EtudiantLabel numEtudiant;
    private fr.miage.toulouse.l3.gestiondesetudiants.view.EtudiantLabel parcoursEtudiant;
    private fr.miage.toulouse.l3.gestiondesetudiants.view.EtudiantLabel prenomEtudiant;
    private javax.swing.JLabel titleDossierLabel1;
    private javax.swing.JLabel titleMentionLabel1;
    private javax.swing.JLabel titleNomLabel1;
    private javax.swing.JLabel titleNumEtudiantLabel1;
    private javax.swing.JLabel titleParcoursLabel1;
    private javax.swing.JLabel titlePrenomLabel1;
    // End of variables declaration//GEN-END:variables
}
