package fr.miage.toulouse.l3.gestiondesetudiants.view;

import javax.swing.JLayeredPane;

/**
 *
 * @author SophiaNachin
 */
public class Principal extends javax.swing.JFrame {

    private static Principal instance;
    /**
     * Creates new form Principal
     */
    
    public synchronized static Principal getInstance(){
        if (instance == null){
            instance = new Principal();
        }
        return instance;
    }
    
    private Principal() {
        initComponents();
        this.setLocationRelativeTo(null); // center the frame
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        navBarPanel = new javax.swing.JPanel();
        SearchBarTextField = new javax.swing.JTextField();
        AccueilButton = new javax.swing.JButton();
        retourButton1 = new fr.miage.toulouse.l3.gestiondesetudiants.controller.RetourButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        bureauExamenListeEtudiantsPanel1 = new fr.miage.toulouse.l3.gestiondesetudiants.view.BureauExamenListeEtudiantsPanel();
        bureauExamenListeUEPanel1 = new fr.miage.toulouse.l3.gestiondesetudiants.view.BureauExamenListeUEPanel();
        directDossierEtudiantPanel1 = new fr.miage.toulouse.l3.gestiondesetudiants.view.DirectDossierEtudiantPanel();
        secretDossierEtudiantPanel1 = new fr.miage.toulouse.l3.gestiondesetudiants.view.SecretDossierEtudiantPanel();
        secretJTableEtudiantsPanel1 = new fr.miage.toulouse.l3.gestiondesetudiants.view.SecretJTableEtudiantsPanel();
        jMenuBar = new javax.swing.JMenuBar();
        FileMenu = new javax.swing.JMenu();
        EditMenu = new javax.swing.JMenu();
        ViewMenu2 = new javax.swing.JMenu();
        HelpMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(252, 252, 252));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 600));

        navBarPanel.setBackground(new java.awt.Color(255, 172, 127));

        SearchBarTextField.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        SearchBarTextField.setForeground(new java.awt.Color(102, 102, 102));
        SearchBarTextField.setText("Rechercher un étudiant");
        SearchBarTextField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        SearchBarTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SearchBarTextFieldMouseClicked(evt);
            }
        });
        SearchBarTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBarTextFieldActionPerformed(evt);
            }
        });

        AccueilButton.setBackground(new java.awt.Color(255, 255, 255));
        AccueilButton.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        AccueilButton.setForeground(new java.awt.Color(51, 51, 51));
        AccueilButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/homepage.png"))); // NOI18N
        AccueilButton.setText("Accueil");
        AccueilButton.setBorderPainted(false);
        AccueilButton.setContentAreaFilled(false);
        AccueilButton.setFocusPainted(false);
        AccueilButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccueilButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout navBarPanelLayout = new javax.swing.GroupLayout(navBarPanel);
        navBarPanel.setLayout(navBarPanelLayout);
        navBarPanelLayout.setHorizontalGroup(
            navBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navBarPanelLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(retourButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(AccueilButton)
                .addGap(228, 228, 228)
                .addComponent(SearchBarTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                .addGap(40, 40, 40))
        );
        navBarPanelLayout.setVerticalGroup(
            navBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navBarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(navBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SearchBarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AccueilButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(retourButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLayeredPane1.setBackground(new java.awt.Color(252, 252, 252));
        jLayeredPane1.setLayout(new java.awt.CardLayout());
        jLayeredPane1.add(bureauExamenListeEtudiantsPanel1, "card2");
        jLayeredPane1.add(bureauExamenListeUEPanel1, "card3");
        jLayeredPane1.add(directDossierEtudiantPanel1, "card4");
        jLayeredPane1.add(secretDossierEtudiantPanel1, "card5");
        jLayeredPane1.add(secretJTableEtudiantsPanel1, "card6");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(navBarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLayeredPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(navBarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane1))
        );

        jMenuBar.setBackground(new java.awt.Color(255, 255, 255));
        jMenuBar.setForeground(new java.awt.Color(51, 51, 51));

        FileMenu.setBackground(new java.awt.Color(255, 255, 255));
        FileMenu.setForeground(new java.awt.Color(51, 51, 51));
        FileMenu.setText("File");
        jMenuBar.add(FileMenu);

        EditMenu.setBackground(new java.awt.Color(255, 255, 255));
        EditMenu.setForeground(new java.awt.Color(51, 51, 51));
        EditMenu.setText("Edit");
        jMenuBar.add(EditMenu);

        ViewMenu2.setBackground(new java.awt.Color(255, 255, 255));
        ViewMenu2.setForeground(new java.awt.Color(51, 51, 51));
        ViewMenu2.setText("View");
        jMenuBar.add(ViewMenu2);

        HelpMenu1.setBackground(new java.awt.Color(255, 255, 255));
        HelpMenu1.setForeground(new java.awt.Color(51, 51, 51));
        HelpMenu1.setText("Help");
        jMenuBar.add(HelpMenu1);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 579, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public BureauExamenListeEtudiantsPanel getBureauExamenListeEtudiantsPanel1() {
        return bureauExamenListeEtudiantsPanel1;
    }

    public BureauExamenListeUEPanel getBureauExamenListeUEPanel1() {
        return bureauExamenListeUEPanel1;
    }

    public DirectDossierEtudiantPanel getDirectDossierEtudiantPanel1() {
        return directDossierEtudiantPanel1;
    }

    public JLayeredPane getjLayeredPane1() {
        return jLayeredPane1;
    }

    public SecretDossierEtudiantPanel getSecretDossierEtudiantPanel1() {
        return secretDossierEtudiantPanel1;
    }

    public SecretJTableEtudiantsPanel getSecretJTableEtudiantsPanel1() {
        return secretJTableEtudiantsPanel1;
    }
    
    
    private void SearchBarTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBarTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchBarTextFieldActionPerformed

    private void AccueilButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccueilButtonActionPerformed
        this.dispose();
        Accueil acc = Accueil.getInstance();
        acc.setVisible(true);
    }//GEN-LAST:event_AccueilButtonActionPerformed

    /**
     * Remplacer le style
     * @param evt 
     */
    private void SearchBarTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchBarTextFieldMouseClicked
        SearchBarTextField.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        SearchBarTextField.setForeground(new java.awt.Color(51, 51, 51));
        SearchBarTextField.setText("");
    }//GEN-LAST:event_SearchBarTextFieldMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AccueilButton;
    private javax.swing.JMenu EditMenu;
    private javax.swing.JMenu FileMenu;
    private javax.swing.JMenu HelpMenu1;
    private javax.swing.JTextField SearchBarTextField;
    private javax.swing.JMenu ViewMenu2;
    private fr.miage.toulouse.l3.gestiondesetudiants.view.BureauExamenListeEtudiantsPanel bureauExamenListeEtudiantsPanel1;
    private fr.miage.toulouse.l3.gestiondesetudiants.view.BureauExamenListeUEPanel bureauExamenListeUEPanel1;
    private fr.miage.toulouse.l3.gestiondesetudiants.view.DirectDossierEtudiantPanel directDossierEtudiantPanel1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel navBarPanel;
    private fr.miage.toulouse.l3.gestiondesetudiants.controller.RetourButton retourButton1;
    private fr.miage.toulouse.l3.gestiondesetudiants.view.SecretDossierEtudiantPanel secretDossierEtudiantPanel1;
    private fr.miage.toulouse.l3.gestiondesetudiants.view.SecretJTableEtudiantsPanel secretJTableEtudiantsPanel1;
    // End of variables declaration//GEN-END:variables
}
