/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fr.miage.toulouse.l3.gestiondesetudiants.view;

import java.io.File;
import java.io.FileInputStream;
import java.io.InputStreamReader;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.apache.commons.csv.CSVFormat;
import org.apache.commons.csv.CSVParser;
import org.apache.commons.csv.CSVRecord;


/**
 *
 * @author SophiaNachin
 */
public class S_DossierEtudiant extends javax.swing.JFrame {   
    
    /**
     * Creates new form DS_DossierEtudiant
     */
    public S_DossierEtudiant() {
        initComponents();
        this.setLocationRelativeTo(null); // center the frame
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        HeaderPanel = new javax.swing.JPanel();
        AccueilButton = new javax.swing.JButton();
        InsButton = new javax.swing.JButton();
        DosButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        SearchBarTextField1 = new javax.swing.JTextField();
        DseLayeredPane1 = new javax.swing.JLayeredPane();
        titleDossierLabel = new javax.swing.JLabel();
        titleNumEtudiantLabel = new javax.swing.JLabel();
        numEtudiantLabel = new javax.swing.JLabel();
        titleNomLabel = new javax.swing.JLabel();
        nomLabel = new javax.swing.JLabel();
        titlePrenomLabel = new javax.swing.JLabel();
        prenomLabel = new javax.swing.JLabel();
        titleNiveauLabel = new javax.swing.JLabel();
        niveauLabel = new javax.swing.JLabel();
        titleMentionLabel = new javax.swing.JLabel();
        mentionLabel = new javax.swing.JLabel();
        titleParcoursLabel = new javax.swing.JLabel();
        parcoursLabel = new javax.swing.JLabel();
        listeUEPanel = new javax.swing.JPanel();
        listeUELabel = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        inscriptionButton = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jToggleButton1 = new javax.swing.JToggleButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        FileMenu = new javax.swing.JMenu();
        EditMenu = new javax.swing.JMenu();
        ViewMenu2 = new javax.swing.JMenu();
        HelpMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        HeaderPanel.setBackground(new java.awt.Color(255, 172, 127));

        AccueilButton.setBackground(new java.awt.Color(255, 191, 153));
        AccueilButton.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        AccueilButton.setForeground(new java.awt.Color(0, 0, 255));
        AccueilButton.setText("Accueil");
        AccueilButton.setBorderPainted(false);
        AccueilButton.setContentAreaFilled(false);
        AccueilButton.setFocusPainted(false);
        AccueilButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccueilButtonActionPerformed(evt);
            }
        });

        InsButton.setBackground(new java.awt.Color(255, 191, 153));
        InsButton.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        InsButton.setForeground(new java.awt.Color(0, 0, 255));
        InsButton.setText("Inscription");
        InsButton.setBorderPainted(false);
        InsButton.setContentAreaFilled(false);
        InsButton.setFocusPainted(false);
        InsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsButtonActionPerformed(evt);
            }
        });

        DosButton.setBackground(new java.awt.Color(255, 191, 153));
        DosButton.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        DosButton.setText("Dossier Étudiant");
        DosButton.setBorderPainted(false);
        DosButton.setContentAreaFilled(false);
        DosButton.setFocusPainted(false);
        DosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DosButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel1.setText(">");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel2.setText(">");

        SearchBarTextField1.setFont(new java.awt.Font("Segoe UI", 2, 13)); // NOI18N
        SearchBarTextField1.setForeground(new java.awt.Color(153, 153, 153));
        SearchBarTextField1.setText("Rechercher un étudiant");
        SearchBarTextField1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(204, 204, 204)));
        SearchBarTextField1.setDisabledTextColor(new java.awt.Color(102, 255, 102));

        javax.swing.GroupLayout HeaderPanelLayout = new javax.swing.GroupLayout(HeaderPanel);
        HeaderPanel.setLayout(HeaderPanelLayout);
        HeaderPanelLayout.setHorizontalGroup(
            HeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderPanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(AccueilButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InsButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DosButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SearchBarTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        HeaderPanelLayout.setVerticalGroup(
            HeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(HeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AccueilButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DosButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(InsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(SearchBarTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        titleDossierLabel.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        titleDossierLabel.setForeground(new java.awt.Color(51, 51, 51));
        titleDossierLabel.setText("Dossier de : ");

        titleNumEtudiantLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        titleNumEtudiantLabel.setForeground(new java.awt.Color(51, 51, 51));
        titleNumEtudiantLabel.setText("N° étudiant");

        numEtudiantLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        numEtudiantLabel.setForeground(new java.awt.Color(51, 51, 51));
        numEtudiantLabel.setText("jLabel3");

        titleNomLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        titleNomLabel.setForeground(new java.awt.Color(51, 51, 51));
        titleNomLabel.setText("Nom");

        nomLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nomLabel.setForeground(new java.awt.Color(51, 51, 51));
        nomLabel.setText("jLabel3");

        titlePrenomLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        titlePrenomLabel.setForeground(new java.awt.Color(51, 51, 51));
        titlePrenomLabel.setText("Prénom");

        prenomLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        prenomLabel.setForeground(new java.awt.Color(51, 51, 51));
        prenomLabel.setText("jLabel3");

        titleNiveauLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        titleNiveauLabel.setForeground(new java.awt.Color(51, 51, 51));
        titleNiveauLabel.setText("Niveau");

        niveauLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        niveauLabel.setForeground(new java.awt.Color(51, 51, 51));
        niveauLabel.setText("jLabel3");

        titleMentionLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        titleMentionLabel.setForeground(new java.awt.Color(51, 51, 51));
        titleMentionLabel.setText("Mention");

        mentionLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mentionLabel.setForeground(new java.awt.Color(51, 51, 51));
        mentionLabel.setText("jLabel3");

        titleParcoursLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        titleParcoursLabel.setForeground(new java.awt.Color(51, 51, 51));
        titleParcoursLabel.setText("Parcours");

        parcoursLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        parcoursLabel.setForeground(new java.awt.Color(51, 51, 51));
        parcoursLabel.setText("jLabel3");

        DseLayeredPane1.setLayer(titleDossierLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DseLayeredPane1.setLayer(titleNumEtudiantLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DseLayeredPane1.setLayer(numEtudiantLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DseLayeredPane1.setLayer(titleNomLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DseLayeredPane1.setLayer(nomLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DseLayeredPane1.setLayer(titlePrenomLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DseLayeredPane1.setLayer(prenomLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DseLayeredPane1.setLayer(titleNiveauLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DseLayeredPane1.setLayer(niveauLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DseLayeredPane1.setLayer(titleMentionLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DseLayeredPane1.setLayer(mentionLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DseLayeredPane1.setLayer(titleParcoursLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DseLayeredPane1.setLayer(parcoursLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout DseLayeredPane1Layout = new javax.swing.GroupLayout(DseLayeredPane1);
        DseLayeredPane1.setLayout(DseLayeredPane1Layout);
        DseLayeredPane1Layout.setHorizontalGroup(
            DseLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DseLayeredPane1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(titleDossierLabel)
                .addGap(24, 24, 24)
                .addGroup(DseLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(numEtudiantLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(titleNumEtudiantLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(DseLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nomLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                    .addComponent(titleNomLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(DseLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titlePrenomLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prenomLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(DseLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DseLayeredPane1Layout.createSequentialGroup()
                        .addComponent(titleNiveauLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 12, Short.MAX_VALUE))
                    .addComponent(niveauLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(DseLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mentionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(DseLayeredPane1Layout.createSequentialGroup()
                        .addComponent(titleMentionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 11, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(DseLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titleParcoursLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(parcoursLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );
        DseLayeredPane1Layout.setVerticalGroup(
            DseLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DseLayeredPane1Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(DseLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleNomLabel)
                    .addComponent(titlePrenomLabel)
                    .addComponent(titleNiveauLabel)
                    .addComponent(titleMentionLabel)
                    .addComponent(titleParcoursLabel)
                    .addComponent(titleDossierLabel)
                    .addComponent(titleNumEtudiantLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DseLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numEtudiantLabel)
                    .addComponent(nomLabel)
                    .addComponent(prenomLabel)
                    .addComponent(niveauLabel)
                    .addComponent(mentionLabel)
                    .addComponent(parcoursLabel))
                .addGap(29, 29, 29))
        );

        listeUEPanel.setBackground(new java.awt.Color(252, 252, 252));

        listeUELabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        listeUELabel.setForeground(new java.awt.Color(51, 51, 51));
        listeUELabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        listeUELabel.setText("Liste des UE disponibles");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(51, 51, 51));
        jLabel20.setText("Trier par");

        jComboBox1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(51, 51, 51));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Parcours", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jComboBox2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboBox2.setForeground(new java.awt.Color(51, 51, 51));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Niveau", "Item 2", "Item 3", "Item 4" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jComboBox3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboBox3.setForeground(new java.awt.Color(51, 51, 51));
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mention", "Item 2", "Item 3", "Item 4" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        jTable4.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jTable4.setForeground(new java.awt.Color(51, 51, 51));
        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sélection", "Code id de l'UE", "Nom UE", "Crédits ECTS", "Mention", "Parcours", "Semestre"
            }
        ));
        jTable4.setGridColor(new java.awt.Color(204, 204, 204));
        jTable4.setSelectionBackground(new java.awt.Color(0, 165, 255));
        jScrollPane4.setViewportView(jTable4);
        if (jTable4.getColumnModel().getColumnCount() > 0) {
            jTable4.getColumnModel().getColumn(0).setPreferredWidth(10);
            jTable4.getColumnModel().getColumn(3).setPreferredWidth(30);
        }

        inscriptionButton.setBackground(new java.awt.Color(255, 90, 0));
        inscriptionButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        inscriptionButton.setForeground(new java.awt.Color(51, 51, 51));
        inscriptionButton.setText("Inscrire");
        inscriptionButton.setFocusPainted(false);
        inscriptionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inscriptionButtonActionPerformed(evt);
            }
        });

        jTextField1.setFont(new java.awt.Font("Segoe UI", 2, 13)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(153, 153, 153));
        jTextField1.setText("jTextField1");

        jToggleButton1.setBackground(new java.awt.Color(0, 165, 255));
        jToggleButton1.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jToggleButton1.setForeground(new java.awt.Color(51, 51, 51));
        jToggleButton1.setText("Chercher");

        javax.swing.GroupLayout listeUEPanelLayout = new javax.swing.GroupLayout(listeUEPanel);
        listeUEPanel.setLayout(listeUEPanelLayout);
        listeUEPanelLayout.setHorizontalGroup(
            listeUEPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listeUEPanelLayout.createSequentialGroup()
                .addGap(385, 385, 385)
                .addComponent(inscriptionButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, listeUEPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(listeUEPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, listeUEPanelLayout.createSequentialGroup()
                        .addComponent(listeUELabel)
                        .addGap(293, 293, 293))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, listeUEPanelLayout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jToggleButton1)
                        .addGap(65, 65, 65))))
            .addGroup(listeUEPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(listeUEPanelLayout.createSequentialGroup()
                    .addGap(62, 62, 62)
                    .addGroup(listeUEPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 734, Short.MAX_VALUE)
                        .addGroup(listeUEPanelLayout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(jLabel20)
                            .addGap(18, 18, 18)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, Short.MAX_VALUE)))
                    .addGap(63, 63, 63)))
        );
        listeUEPanelLayout.setVerticalGroup(
            listeUEPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, listeUEPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(listeUELabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(listeUEPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 326, Short.MAX_VALUE)
                .addComponent(inscriptionButton)
                .addGap(13, 13, 13))
            .addGroup(listeUEPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(listeUEPanelLayout.createSequentialGroup()
                    .addGap(55, 55, 55)
                    .addGroup(listeUEPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel20)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(64, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HeaderPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(DseLayeredPane1)
            .addComponent(listeUEPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(HeaderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DseLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(listeUEPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));

        FileMenu.setBackground(new java.awt.Color(255, 255, 255));
        FileMenu.setForeground(new java.awt.Color(51, 51, 51));
        FileMenu.setText("File");
        jMenuBar1.add(FileMenu);

        EditMenu.setBackground(new java.awt.Color(255, 255, 255));
        EditMenu.setForeground(new java.awt.Color(51, 51, 51));
        EditMenu.setText("Edit");
        jMenuBar1.add(EditMenu);

        ViewMenu2.setBackground(new java.awt.Color(255, 255, 255));
        ViewMenu2.setForeground(new java.awt.Color(51, 51, 51));
        ViewMenu2.setText("View");
        jMenuBar1.add(ViewMenu2);

        HelpMenu1.setBackground(new java.awt.Color(255, 255, 255));
        HelpMenu1.setForeground(new java.awt.Color(51, 51, 51));
        HelpMenu1.setText("Help");
        jMenuBar1.add(HelpMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DosButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DosButtonActionPerformed

    private void InsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InsButtonActionPerformed

    private void AccueilButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccueilButtonActionPerformed
        this.dispose();
        Accueil acc = new Accueil();
        acc.setVisible(true);
    }//GEN-LAST:event_AccueilButtonActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void inscriptionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inscriptionButtonActionPerformed
        int reponse = JOptionPane.showConfirmDialog(null, "Voulez-vous confirmer l'inscription ?", "confirm", JOptionPane.YES_NO_OPTION );
        if (reponse == JOptionPane.YES_OPTION){
            JOptionPane.showMessageDialog(null, "InscriptionReussi");
        }
        else{
            
        }
        
    }//GEN-LAST:event_inscriptionButtonActionPerformed
    
    
    public javax.swing.JLabel getnumEtudiantLabel(){
        return this.numEtudiantLabel;
    }
    
    public javax.swing.JLabel getNomLabel(){
        return this.nomLabel;
    }
    
    public javax.swing.JLabel getPrenomLabel(){
        return this.prenomLabel;
    }
    
    public javax.swing.JLabel getNiveauLabel(){
        return this.niveauLabel;
    }
    
    public javax.swing.JLabel getMentionLabel(){
        return this.mentionLabel;
    }
    
    public javax.swing.JLabel getParcoursLabel(){
        return this.parcoursLabel;
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(S_DossierEtudiant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(S_DossierEtudiant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(S_DossierEtudiant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(S_DossierEtudiant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

    }
    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AccueilButton;
    private javax.swing.JButton DosButton;
    private javax.swing.JLayeredPane DseLayeredPane1;
    private javax.swing.JMenu EditMenu;
    private javax.swing.JMenu FileMenu;
    private javax.swing.JPanel HeaderPanel;
    private javax.swing.JMenu HelpMenu1;
    private javax.swing.JButton InsButton;
    private javax.swing.JTextField SearchBarTextField1;
    private javax.swing.JMenu ViewMenu2;
    private javax.swing.JButton inscriptionButton;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel listeUELabel;
    private javax.swing.JPanel listeUEPanel;
    private javax.swing.JLabel mentionLabel;
    private javax.swing.JLabel niveauLabel;
    private javax.swing.JLabel nomLabel;
    private javax.swing.JLabel numEtudiantLabel;
    private javax.swing.JLabel parcoursLabel;
    private javax.swing.JLabel prenomLabel;
    private javax.swing.JLabel titleDossierLabel;
    private javax.swing.JLabel titleMentionLabel;
    private javax.swing.JLabel titleNiveauLabel;
    private javax.swing.JLabel titleNomLabel;
    private javax.swing.JLabel titleNumEtudiantLabel;
    private javax.swing.JLabel titleParcoursLabel;
    private javax.swing.JLabel titlePrenomLabel;
    // End of variables declaration//GEN-END:variables
}
