package fr.miage.toulouse.l3.gestiondesetudiants.view;

/**
 *  
 * @author SophiaNachin
 */
public class SecretJTableEtudiantsPanel extends javax.swing.JPanel {
    /**
     * Creates new form BureauExamenListeEtudiantsPanel
     */
    public SecretJTableEtudiantsPanel() {
        initComponents(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        listeEtudiantLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listeEtudiantTable1 = new fr.miage.toulouse.l3.gestiondesetudiants.view.ListeEtudiantTable();

        setBackground(new java.awt.Color(252, 252, 252));
        setPreferredSize(new java.awt.Dimension(709, 509));

        listeEtudiantLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        listeEtudiantLabel.setForeground(new java.awt.Color(51, 51, 51));
        listeEtudiantLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        listeEtudiantLabel.setText("Liste des étudiants");

        jScrollPane1.setViewportView(listeEtudiantTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(listeEtudiantLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(listeEtudiantLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Récupère les données de l'étudiant sélectionné, pour pouvoir les passer 
     * au controleur
     * @param evt 
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel listeEtudiantLabel;
    private fr.miage.toulouse.l3.gestiondesetudiants.view.ListeEtudiantTable listeEtudiantTable1;
    // End of variables declaration//GEN-END:variables
}
